import type { Metadata } from "next";
import { Inter, Montserrat,Open_Sans } from "next/font/google";
import "./globals.css";
import Footer from "./components/layout/Footer";
import Header from "./components/layout/Header";

const inter = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ua">
      <body className={inter.className}>
          <Header/>
        <main>
        {children}
        </main>
          <Footer/>

        </body>
    </html>
  );
}
